CREATE TABLE MEMBER
(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_USERID VARCHAR2(20) UNIQUE NOT NULL,
    MEMBER_USERPWD CHAR(20) NOT NULL,
    MEMBER_NICKNAME VARCHAR2(20) UNIQUE NOT NULL,
    MEMBER_GENDER NVARCHAR2(1) CHECK (MEMBER_GENDER IN ('남','여')),
    MEMBER_EMAIL VARCHAR2(30) NOT NULL
);

CREATE TABLE BOARD
(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(20) NOT NULL,
    BOARD_CONTENT VARCHAR2(200) NOT NULL,
    BOARD_WRITEDATE DATE NOT NULL,
    BOARD_NICKNAME VARCHAR2(20) NOT NULL,
    FOREIGN KEY (BOARD_NICKNAME) REFERENCES MEMBER (MEMBER_NICKNAME)
);

CREATE SEQUENCE MB_MB_NO
START WITH 1000
INCREMENT BY 1
MAXVALUE 1000000
NOCYCLE
NOCACHE;

CREATE SEQUENCE BOARD_BO_NO
START WITH 1
INCREMENT BY 1
MAXVALUE 500000
NOCYCLE
NOCACHE;

CREATE VIEW VIEW_MEMBER
AS SELECT MEMBER_NO, MEMBER_NICKNAME, MEMBER_EMAIL, BOARD_TITLE
FROM MEMBER JOIN BOARD ON (MEMBER_NICKNAME=BOARD_NICKNAME);

CREATE INDEX BOARD_INDEX ON BOARD(BOARD_TITLE,BOARD_CONTENT);

CREATE SYNONYM M FOR MEMBER;

CREATE SYNONYM B FOR BOARD;

INSERT INTO MEMBER
VALUES(MB_MB_NO.NEXTVAL,'USER1','PASS1','MEMBER1','남','USER1@KH.OR.KR');
INSERT INTO MEMBER
VALUES(MB_MB_NO.NEXTVAL,'USER2','PASS2','MEMBER2','남','USER1@KH.OR.KR');
INSERT INTO MEMBER
VALUES(MB_MB_NO.NEXTVAL,'USER3','PASS3','MEMBER3','여','USER1@KH.OR.KR');
INSERT INTO MEMBER
VALUES(MB_MB_NO.NEXTVAL,'USER4','PASS4','MEMBER4','남','USER1@KH.OR.KR');

SELECT * FROM M;
SELECT * FROM B;

INSERT INTO BOARD
VALUES(BOARD_BO_NO.NEXTVAL,'가나다','1234가',SYSDATE,'MEMBER3');
INSERT INTO BOARD
VALUES(BOARD_BO_NO.NEXTVAL,'아자차','784나',SYSDATE,'MEMBER1');
INSERT INTO BOARD
VALUES(BOARD_BO_NO.NEXTVAL,'타파하','다가다',SYSDATE,'MEMBER4');

SELECT * FROM VIEW_MEMBER;

SELECT * FROM USER_IND_COLUMNS;

