GRANT SELECT ON kh.EMPLOYEE_HEALTH TO khlove1;
GRANT CREATE VIEW TO KH;
GRANT SELECT ON kh.EMP_HEALTH_VIEW TO khlove1;
GRANT SELECT ON KH.EMP_INFO_VIEW TO KHLOVE1;

-- SYNONYM 권한을 KH한테 줌
GRANT CREATE SYNONYM TO kh;

-- 공개 동의어
CREATE PUBLIC SYNONYM DEPT FOR KH.DEPARTMENT;

GRANT SELECT ON DEPT TO KHLOVE1;

CREATE USER khtest identified by khtest;

grant resource, connect to khtest;

GRANT CREATE VIEW TO khtest;

GRANT CREATE SYNONYM TO khtest;