SELECT DEPT_CODE, SUM(SALARY), FLOOR(AVG(SALARY))
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT JOB_CODE, SUM(SALARY), SUM(SALARY)*12
FROM EMPLOYEE
GROUP BY JOB_CODE;

SELECT DEPT_CODE, SUM(SALARY), FLOOR(AVG(SALARY)), COUNT(*)
FROM EMPLOYEE
GROUP BY DEPT_CODE
ORDER BY 1;

SELECT DEPT_CODE, COUNT(*)
FROM EMPLOYEE
WHERE BONUS IS NOT NULL
GROUP BY DEPT_CODE
ORDER BY 1;

SELECT JOB_CODE, COUNT(*), FLOOR(AVG(SALARY))
FROM EMPLOYEE
WHERE JOB_CODE NOT LIKE 'J1'
GROUP BY JOB_CODE;

SELECT DEPT_CODE, 
DECODE(SUBSTR(EMP_NO,8,1),'1','남자','여자')AS "성별",
COUNT(*) AS "인원"
FROM EMPLOYEE
GROUP BY DEPT_CODE, SUBSTR(EMP_NO,8,1)
ORDER BY DEPT_CODE;

SELECT DEPT_CODE, FLOOR(AVG(SALARY))
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING FLOOR(AVG(SALARY))>=3000000;

-- 부서별 인원 정보 출력
SELECT DEPT_CODE,COUNT(*)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

-- 집계를 하고 싶다면???
SELECT DEPT_CODE,COUNT(*)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE)
ORDER BY 1;

SELECT DEPT_CODE,COUNT(*)
FROM EMPLOYEE
GROUP BY CUBE(DEPT_CODE)
ORDER BY 1;

-- 부서내 평균연봉과 집계
SELECT DEPT_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE);

-- 직급별 평균연봉과 집계
SELECT JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY ROLLUP(JOB_CODE);

-- 이번에는 부서내 직급별 인원 정보를 출력하고 싶다면?
SELECT DEPT_CODE, JOB_CODE, COUNT(*)
FROM EMPLOYEE
GROUP BY DEPT_CODE, JOB_CODE
ORDER BY 1;

-- 집계를 하고 싶다면? (ROLLUP을 사용)
SELECT DEPT_CODE, JOB_CODE, COUNT(*)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE, JOB_CODE)
ORDER BY 1;

-- ROLLUP을 사용하게 되면 부서별 집계 및 총 집계를 확인 할 수 있음
-- ROLLUP은 가장 먼저 지정한 그룹별 집계와 총 집계를 구하는 함수

-- 만약 부서별이 아닌 직급별 집계와 총 집계를 보고 싶다면??
-- JOB_CODE 위치와 DEPT_CODE 위치를 바꾸어 주면 됨

SELECT JOB_CODE, DEPT_CODE, COUNT(*)
FROM EMPLOYEE
GROUP BY ROLLUP(JOB_CODE, DEPT_CODE)
ORDER BY 1;

-- 내가 보고 싶은건!
-- 직급별 집계와 직급별 집계 및 총 집계

SELECT DEPT_CODE, JOB_CODE, COUNT(*)
FROM EMPLOYEE
GROUP BY CUBE(DEPT_CODE, JOB_CODE)
ORDER BY 1;

-- CUBE 는 그룹으로 지정된 모든 그룹에 대한 집계와 총 집계를 구함
-- 즉, 위에 코드를 보면 부서별 집계 이후에 직급별 집계를 진행하고 마지막으로
-- 총 집계를 구하게 됨

-- 직관적으로 이야기 하면!
-- ROLLUP과 CUBE는 집계용 함수
-- ROLLUP은 가장 먼저 지정한 그룹별 집계 및 총 집계
-- CUBE는 그룹으로 지정된 모든 그룹에 대한 그룹별 집계 및 총 집계

-- 문제1 부서내 직급별 급여 정보 출력 및 각 부서별 집계
SELECT DEPT_CODE, JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE, JOB_CODE)
ORDER BY 1;

-- 문제2 부서내 직급별 급여 정보 출력 및 각 부서별 집계 및 직급별 집계
SELECT DEPT_CODE,COUNT(*)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE)
ORDER BY 1;

SELECT DEPT_CODE, COUNT(*), GROUPING(DEPT_CODE)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE);

SELECT DEPT_CODE, COUNT(*), DECODE(GROUPING(DEPT_CODE),1,'총 집계','부서별')
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE);

SELECT DECODE(GROUPING(DEPT_CODE),0,NVL(DEPT_CODE,'부서없음'),DEPT_CODE,1,'총 집계') AS "부서코드",COUNT(*)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE);

SELECT DEPT_CODE,JOB_CODE, COUNT(*),
CASE WHEN GROUPING(DEPT_CODE)=0 AND GROUPING(JOB_CODE) =1 THEN '부서별 집계'
WHEN GROUPING(DEPT_CODE)=1 AND GROUPING(JOB_CODE) =0 THEN '직급별 집계'
WHEN GROUPING(DEPT_CODE)=1 AND GROUPING(JOB_CODE) =1 THEN '총 집계'
ELSE ' '
END AS "집계 현황"
FROM EMPLOYEE
GROUP BY CUBE(DEPT_CODE,JOB_CODE)
ORDER BY 1;

SELECT DEPT_CODE,JOB_CODE, COUNT(*),
GROUPING(DEPT_CODE),GROUPING(JOB_CODE)
FROM EMPLOYEE
GROUP BY CUBE(DEPT_CODE,JOB_CODE)
ORDER BY 1;

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM JOB;

SELECT EMP_NAME, DEPT_CODE
FROM EMPLOYEE
WHERE EMP_NAME='선동일';

SELECT DEPT_TITLE
FROM DEPARTMENT
WHERE DEPT_ID='D9';

SELECT EMP_NAME,DEPT_CODE,DEPT_TITLE
FROM EMPLOYEE,DEPARTMENT
WHERE DEPT_ID = DEPT_CODE AND EMP_NAME='선동일';

SELECT EMP_NAME,DEPT_CODE,DEPT_TITLE
FROM DEPARTMENT,EMPLOYEE
WHERE DEPT_ID = DEPT_CODE;

SELECT EMP_NAME, DEPT_TITLE, DEPT_CODE, DEPT_ID
FROM EMPLOYEE INNER JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);

SELECT EMP_NAME, DEPT_TITLE, DEPT_CODE, DEPT_ID
FROM EMPLOYEE LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);