-- Basic SELECT
-- 1
SELECT DEPARTMENT_NAME AS "학과 명",
CATEGORY AS "계열"
FROM TB_DEPARTMENT;

-- 2
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

-- 3
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001' AND
SUBSTR(STUDENT_SSN,8,1)=2 AND
TB_STUDENT.ABSENCE_YN = 'Y';

-- 4
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY 1 DESC;

-- 5
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7
SELECT * FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9
SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT; 

-- 10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주시%' AND
ABSENCE_YN = 'N' AND
SUBSTR(ENTRANCE_DATE,1,2)=02;

-- SELECT 함수
-- 1
SELECT STUDENT_NO AS "학번",
STUDENT_NAME AS "이름",
ENTRANCE_DATE AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 3;

-- 2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3
SELECT PROFESSOR_NAME AS "교수이름",
EXTRACT(YEAR FROM SYSDATE) - (19||SUBSTR(PROFESSOR_SSN,1,2)) AS "나이"
FROM TB_PROFESSOR
ORDER BY 2;

-- 4
SELECT SUBSTR(PROFESSOR_NAME,2,2) AS "이름"
FROM TB_PROFESSOR;

-- 5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)-(19||SUBSTR(STUDENT_SSN,1,2))=20;

-- 6
SELECT TO_CHAR(TO_DATE(20201225,'YYYY/MM/DD'),'DAY')
FROM DUAL;

-- 7
SELECT TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'),'YYYY"년"MM"월"DD"일"')AS "년 월 일",
TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'),'YYYY"년"MM"월"DD"일"')AS "년 월 일",
TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'),'YYYY"년"MM"월"DD"일"')AS "년 월 일",
TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'),'YYYY"년"MM"월"DD"일"')AS "년 월 일"
FROM DUAL;

-- 8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

-- 9
SELECT ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10
SELECT DEPARTMENT_NO AS "학과번호",
COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO;

-- 11
SELECT COUNT(*)
FROM TB_STUDENT
GROUP BY COACH_PROFESSOR_NO
HAVING COACH_PROFESSOR_NO IS NULL;

-- 12
SELECT SUBSTR(TERM_NO,1,4) AS "년도", 
ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
GROUP BY SUBSTR(TERM_NO,1,4),STUDENT_NO
HAVING STUDENT_NO IN ('A112113');

-- 13
SELECT DEPARTMENT_NO AS "학과코드명",
SUM(DECODE(ABSENCE_YN,'Y',1,0)) AS "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO;

-- 14
SELECT STUDENT_NAME AS "동일이름",
COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) != 1;

-- 15
SELECT NVL(SUBSTR(TERM_NO,1,4),' ') AS "년도",
NVL(SUBSTR(TERM_NO,5,2),' ') AS "학기",
ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO='A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2));

-- Additional SELECT - Option
-- 1
SELECT STUDENT_NAME AS "학생 이름",
STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY 1;

-- 2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 1 DESC;

-- 3
SELECT STUDENT_NAME AS "학생이름",
STUDENT_NO AS "학번",
STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '%경기도%' OR STUDENT_ADDRESS LIKE '%강원도%') AND
(ENTRANCE_DATE BETWEEN '1900/01/01' AND '1999/12/31')
ORDER BY 1;

-- 4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO='005'
ORDER BY 2;

-- 5
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100' AND TERM_NO=200402
ORDER BY 2 DESC, 1 ASC;

-- 6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;

-- 7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

-- 8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
ORDER BY 2;

-- 9
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C, TB_CLASS_PROFESSOR CP, TB_PROFESSOR P, TB_DEPARTMENT D
WHERE C.CLASS_NO=CP.CLASS_NO AND CP.PROFESSOR_NO=P.PROFESSOR_NO
AND P.DEPARTMENT_NO=D.DEPARTMENT_NO AND CATEGORY = '인문사회'
ORDER BY 2;

-- 10
SELECT S.STUDENT_NO AS "학번",
STUDENT_NAME AS "학생 이름",
ROUND(AVG(POINT),1) AS "전체 평점"
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_GRADE G
WHERE S.DEPARTMENT_NO=D.DEPARTMENT_NO AND
S.STUDENT_NO=G.STUDENT_NO AND
D.DEPARTMENT_NAME='음악학과'
GROUP BY (S.STUDENT_NO,STUDENT_NAME);

-- 11
SELECT DEPARTMENT_NAME AS "학과이름",
STUDENT_NAME AS "학생이름",
PROFESSOR_NAME AS "지도교수이름"
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR P
WHERE S.DEPARTMENT_NO=D.DEPARTMENT_NO AND
S.COACH_PROFESSOR_NO=P.PROFESSOR_NO AND
S.STUDENT_NO='A313047';

-- 12
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE CLASS_NAME = '인간관계론' AND SUBSTR(TERM_NO,1,4)=2007;

-- 13
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL;

-- 14
SELECT STUDENT_NAME AS "학생이름",
NVL(PROFESSOR_NO,'지도교수 미지정') AS "지도교수"
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR P
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO AND
S.COACH_PROFESSOR_NO=P.PROFESSOR_NO(+) AND
D.DEPARTMENT_NAME='서반아어학과';

-- 15
SELECT STUDENT_NO AS "학번",
STUDENT_NAME AS "이름",
DEPARTMENT_NAME AS "학과 이름",
ROUND(AVG(POINT),5) AS "평점"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN='N'
GROUP BY (STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME)
HAVING AVG(POINT)>=4.0;

-- 16
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),6)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_DEPARTMENT ON (TB_DEPARTMENT.DEPARTMENT_NO=TB_CLASS.DEPARTMENT_NO)
WHERE CLASS_TYPE LIKE '전공%' AND DEPARTMENT_NAME='환경조경학과'
GROUP BY (CLASS_NO,CLASS_NAME);

-- 17
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
FROM TB_STUDENT WHERE STUDENT_NAME='최경희');

-- 18
WITH TOP_N AS(SELECT S.STUDENT_NO, STUDENT_NAME, AVG(POINT)
FROM TB_STUDENT S, TB_GRADE G, TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO=D.DEPARTMENT_NO AND
S.STUDENT_NO = G.STUDENT_NO AND D.DEPARTMENT_NAME='국어국문학과'
GROUP BY S.STUDENT_NO, STUDENT_NAME
ORDER BY 3 DESC)

SELECT STUDENT_NO, STUDENT_NAME
FROM TOP_N
WHERE ROWNUM =1;


-- 19
SELECT * FROM TB_DEPARTMENT;    --학과
SELECT * FROM TB_STUDENT;       --학생   
SELECT * FROM TB_CLASS;         --과목
SELECT * FROM TB_CLASS_PROFESSOR;       --과목 교수
SELECT * FROM TB_PROFESSOR;     --교수
SELECT * FROM TB_GRADE;         --성적
SELECT  D.DEPARTMENT_NAME AS 계열학과명, ROUND(AVG(G.POINT),1) AS 전공평점
FROM TB_DEPARTMENT D JOIN TB_CLASS C ON (D.DEPARTMENT_NO = C.DEPARTMENT_NO)
                     JOIN TB_GRADE G ON (C.CLASS_NO = G.CLASS_NO) 
                     JOIN TB_STUDENT S ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE D.CATEGORY = (SELECT CATEGORY FROM TB_DEPARTMENT
                            WHERE DEPARTMENT_NAME  = '환경조경학과')
GROUP BY D.DEPARTMENT_NAME;

-- DDL
-- 1
CREATE TABLE TB_CATEGORY
(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2
CREATE TABLE TB_CLASS_TYPE
(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3
ALTER TABLE TB_CATEGORY
ADD CONSTRAINT NAME_P PRIMARY KEY(NAME);

-- 4
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME CONSTRAINT NAME_NN NOT NULL;

SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME='TB_CLASS_TYPE'
UNION
SELECT TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='TB_CLASS_TYPE'
ORDER BY 3 DESC;

-- 5
ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

-- 6
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO  CLASS_TYPE_NO;
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

-- 7
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN CLASS_TYPE_NO TO PK_CLASS_TYPE_NO;
ALTER TABLE TB_CATEGORY
RENAME COLUMN CATEGORY_NAME TO PK_CATEGORY_NAME;

-- 8
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

-- 9
