select * from tabs;

select job_name from job;

select * from DEPARTMENT;

select emp_name,email,phone,hire_date from employee;

select emp_name, hire_date, salary from employee;

select emp_name,sal_level from employee where salary>=2500000;

select emp_name,phone from employee where salary>=3500000 and job_code='J3';

select * from employee;

SELECT EMP_NAME,SALARY*12 FROM EMPLOYEE;

SELECT EMP_NAME,SALARY*BONUS FROM EMPLOYEE;

SELECT EMP_NAME AS 이름,((SALARY*BONUS)+SALARY)*12 AS "연봉(원)" FROM EMPLOYEE;

SELECT EMP_NAME AS 이름, SALARY*12 AS "연봉", '원' AS "단위" FROM EMPLOYEE;

SELECT EMP_NAME AS "이름", SALARY*12 AS "연봉", ((salary*bonus)+salary)*12 AS "총수령액",
(((salary*bonus)+salary)*12)-(SALARY*0.03)*12 AS "실수령액"  FROM EMPLOYEE;

SELECT EMP_NAME,NVL(BONUS,0) FROM EMPLOYEE;

SELECT EMP_NAME AS "이름", FLOOR(SYSDATE-HIRE_DATE) AS "근무일수", '일' FROM EMPLOYEE;

SELECT EMP_NAME AS "이름", SALARY AS "월급", NVL(BONUS,0)*100 ||'%' AS "보너스율" FROM EMPLOYEE WHERE (SYSDATE-HIRE_DATE)/365 >= 20;

SELECT * FROM EMPLOYEE;

SELECT DEPT_CODE FROM EMPLOYEE;

SELECT DISTINCT DEPT_CODE FROM EMPLOYEE;

SELECT EMP_NAME, SALARY||'원' AS "월급" FROM EMPLOYEE;

SELECT EMP_NAME, '폰번호 : ' || PHONE AS "휴대폰" FROM EMPLOYEE;

SELECT EMP_NAME, '급여 : ' || SALARY || '/보너스율 : ' || NVL(BONUS,0)*100 ||'%' AS "급여및보너스율" FROM EMPLOYEE;

SELECT EMP_NAME,SALARY
FROM EMPLOYEE
WHERE 3500000<= SALARY AND SALARY <= 6000000;

SELECT EMP_NAME,SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 3500000 AND 6000000;

SELECT * FROM EMPLOYEE;

SELECT EMP_NAME, HIRE_DATE AS "고용일"
FROM EMPLOYEE 
WHERE HIRE_DATE BETWEEN '90/01/01' AND '01/01/01';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '이__';

SELECT * FROM EMPLOYEE WHERE EMP_NAME NOT LIKE '이%';

SELECT * FROM EMPLOYEE WHERE PHONE LIKE '%3%';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '%연';
SELECT EMP_NAME,PHONE FROM EMPLOYEE WHERE PHONE NOT LIKE '010%';
SELECT * FROM EMPLOYEE WHERE EMAIL LIKE '____/_%' ESCAPE '/' AND 
(DEPT_CODE='D9' OR DEPT_CODE='D6')
AND (HIRE_DATE BETWEEN '90/01/01' AND '00/12/01')
AND SALARY>=2700000;

SELECT * 
FROM EMPLOYEE
WHERE EMAIL LIKE '%s%' ESCAPE '/' AND 
(DEPT_CODE='D9' OR DEPT_CODE='D6')
AND (HIRE_DATE BETWEEN '90/01/01' AND '00/12/01')
AND SALARY>=2700000;

SELECT EMAIL, SALARY FROM EMPLOYEE;


SELECT * FROM EMPLOYEE WHERE BONUS IS NULL;
SELECT * FROM EMPLOYEE WHERE BONUS IS NOT NULL;

SELECT * FROM EMPLOYEE;

SELECT EMP_NAME FROM EMPLOYEE WHERE MANAGER_ID IS NULL AND DEPT_CODE IS NULL;

SELECT EMP_NAME FROM EMPLOYEE WHERE DEPT_CODE IS NULL AND BONUS IS NOT NULL;

SELECT * FROM EMPLOYEE WHERE DEPT_CODE IN ('D6','D9');

SELECT EMP_NAME, SALARY, JOB_CODE FROM EMPLOYEE WHERE JOB_CODE IN ('J7','J2') AND SALARY>2000000;

SELECT * FROM EMPLOYEE ORDER BY 2;

SELECT BONUS*SALARY FROM EMPLOYEE ORDER BY 1 DESC;

SELECT * FROM EMPLOYEE;

SELECT EMP_NAME, EMP_NO, SALARY, HIRE_DATE FROM EMPLOYEE WHERE (SYSDATE-HIRE_DATE)/365 BETWEEN 5 AND 10;

SELECT EMP_NAME, DEPT_CODE, HIRE_DATE, ENT_DATE-HIRE_DATE, ENT_DATE FROM EMPLOYEE WHERE ENT_YN='Y';

SELECT EMP_NAME, SALARY, FLOOR((SYSDATE-HIRE_DATE)/365) AS "근속년수" FROM EMPLOYEE WHERE (SYSDATE-HIRE_DATE)/365>=10 ORDER BY "근속년수" ASC;

SELECT EMP_NAME, EMP_NO, EMAIL, PHONE, SALARY FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN '99/01/01' AND '10/01/01' AND SALARY<=2000000;

SELECT EMP_NAME, EMP_NO, SALARY, NVL(DEPT_CODE,'없음')
FROM EMPLOYEE WHERE (SALARY BETWEEN '2000000' AND '3000000')
AND EMP_NO LIKE '__04__-2%'
ORDER BY 2 DESC;

SELECT EMP_NAME as "이름",
FLOOR((SYSDATE-HIRE_DATE)/1000)*SALARY*0.1 ||'원'AS "특별보너스"
FROM EMPLOYEE
WHERE EMP_NO LIKE '%-1%' AND BONUS IS NULL
ORDER BY EMP_NAME;

SELECT EMAIL, LENGTH(EMAIL) AS "이메일 길이"
FROM EMPLOYEE;



SELECT JOB_NAME FROM JOB;

SELECT * FROM DEPARTMENT;

SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE FROM EMPLOYEE;

SELECT HIRE_DATE, EMP_NAME, SALARY FROM EMPLOYEE;

SELECT EMP_NAME, SAL_LEVEL FROM EMPLOYEE WHERE SALARY>=2500000;

SELECT EMP_NAME, PHONE FROM EMPLOYEE WHERE SALARY>=3500000 AND JOB_CODE='J3';



SELECT EMP_NAME AS "이름", 
SALARY*12 AS "연봉", 
(SALARY*12)+(SALARY*BONUS*12) AS "총수령액",
(SALARY*12)+(SALARY*BONUS*12)-(SALARY*0.03*12) AS "실수령액"
FROM EMPLOYEE;

SELECT EMP_NAME AS "이름", (SYSDATE-HIRE_DATE) AS "근무 일수" FROM EMPLOYEE;

SELECT EMP_NAME AS "이름", SALARY AS "월급",
NVL(BONUS,0)*100 AS "보너스율", '%'
FROM EMPLOYEE
WHERE (SYSDATE-HIRE_DATE)/365>=20;

SELECT EMP_NAME AS "이름" FROM EMPLOYEE WHERE EMP_NAME LIKE '%연';

SELECT EMP_NAME, PHONE FROM EMPLOYEE WHERE PHONE NOT LIKE '010%';

SELECT * 
FROM EMPLOYEE 
WHERE (EMAIL LIKE '%s%') 
AND (DEPT_CODE='D9' OR DEPT_CODE='D6')
AND (HIRE_DATE BETWEEN '90/01/01' AND '00/12/01')
AND SALARY>=2700000;


SELECT EMP_NAME, LENGTH(EMP_NAME), LENGTHB(EMP_NAME) FROM EMPLOYEE;

SELECT INSTR('Hello World Hi High', 'H',1,1) FROM DUAL;
SELECT INSTR('Hello World Hi High', 'H',1,2) FROM DUAL;
SELECT INSTR('Hello World Hi High', 'H',1,3) FROM DUAL;
SELECT INSTR('Hello World Hi High', 'H',1,4) FROM DUAL;

SELECT INSTR(EMAIL, '@') FROM EMPLOYEE;

SELECT RPAD('mslove',20,'@') FROM DUAL;

SELECT RPAD(EMAIL,20) FROM EMPLOYEE;

SELECT LPAD(EMAIL,20) FROM EMPLOYEE;

SELECT LTRIM('0000000000KHLOVE0','0') FROM DUAL;

SELECT LTRIM('123321KH','123') FROM DUAL;
SELECT LTRIM('12312332112321313121KH','123') FROM DUAL;

SELECT TRIM ('  KH  ') FROM DUAL;

SELECT TRIM('Z'FROM'ZZKHZZ') FROM DUAL;
SELECT TRIM(LEADING'Z'FROM'ZZKHZZ') FROM DUAL;
SELECT TRIM(TRAILING'Z'FROM'ZZKHZZ') FROM DUAL;
SELECT TRIM(BOTH 'Z'FROM'ZZKHZZ') FROM DUAL;

SELECT RTRIM('Hello KH Java',' Java') FROM DUAL;

SELECT LTRIM('Hello KH Java','Hello ') FROM DUAL;

SELECT DEPT_TITLE FROM DEPARTMENT;

SELECT TRIM(TRAILING'부' FROM DEPT_TITLE) FROM DEPARTMENT;

SELECT LTRIM(RTRIM('982341678934509hello89798739273402', '0123456789'),'0123456789') FROM DUAL;

SELECT SUBSTR('SHOWMETHEMONEY',5,2) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY',5) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY',1,6) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY',-8,3) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY',1,6) FROM DUAL;
SELECT SUBSTR('쇼미더머니',1,2) FROM DUAL;

SELECT EMP_NAME,SUBSTR(EMP_NO,1,6) FROM EMPLOYEE;

SELECT DISTINCT SUBSTR(EMP_NAME,1,1) FROM EMPLOYEE ORDER BY SUBSTR(EMP_NAME,1,1) ASC;