SELECT * FROM COPY_EMPLOYEE;

DELETE
FROM COPY_EMPLOYEE
WHERE EMP_ID = (SELECT EMP_ID FROM COPY_EMPLOYEE WHERE SALARY=2000000 AND EMP_NAME ='전형돈');

CREATE TABLE MEMBER_TEST01
(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) UNIQUE,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30)
);

INSERT INTO MEMBER_TEST01
VALUES(1,'USER11','1111','홍길동');
INSERT INTO MEMBER_TEST01
VALUES(2,'USER22','2222','김말똥');
INSERT INTO MEMBER_TEST01
VALUES(3,'USER33','3333','고길똥');

CREATE TABLE MEMBER_FOREIGN
(
    USER_ID VARCHAR2(20),
    REGDATE DATE,
    FOREIGN KEY (USER_ID) REFERENCES MEMBER_TEST01 (USER_ID)
);

INSERT INTO MEMBER_FOREIGN
VALUES('USER11',SYSDATE);
INSERT INTO MEMBER_FOREIGN
VALUES('USER22',SYSDATE);
INSERT INTO MEMBER_FOREIGN
VALUES('USER33',SYSDATE);

SELECT * FROM MEMBER_TEST01;
SELECT * FROM MEMBER_FOREIGN;

DELETE FROM MEMBER_TEST01
WHERE USER_ID='USER11';

-- 제약조건 확인
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME='MEMBER_FOREIGN'
UNION
SELECT TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='MEMBER_FOREIGN'
ORDER BY 3 DESC;

-- 제약조건 비활성화
ALTER TABLE MEMBER_FOREIGN
DISABLE CONSTRAINT SYS_C007096;

-- 제약조건 활성화
ALTER TABLE MEMBER_FOREIGN
ENABLE CONSTRAINT SYS_C007096;

DELETE FROM MEMBER_FOREIGN
WHERE USER_ID = 'USER11';


SELECT * FROM MEMBER_FOREIGN;

DELETE FROM MEMBER_FOREIGN;

ROLLBACK;

TRUNCATE TABLE MEMBER_FOREIGN;


CREATE TABLE khacademy
(
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(20) UNIQUE,
    PASS VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    NICKNAME VARCHAR2(20) UNIQUE,
    GENDER CHAR(1) CHECK (GENDER IN ('M','F')),
    TEL VARCHAR(20) DEFAULT '010-0000-0000',
    ADDRESS VARCHAR2(90)
);

INSERT INTO KHACADEMY
VALUES(1,'hong11','1234','홍길동','동해번쩍','M','010-4958-2333','경기도');
INSERT INTO KHACADEMY
VALUES(2,'gogo11','4444','고길똥','둘리세퀴','M',default,'경상도');
INSERT INTO KHACADEMY
VALUES(3,'kimDDong','6658','김말똥','내눈은말똥','F','010-6674-8986','전라도');
INSERT INTO KHACADEMY
VALUES(4,'sin','5356','신구','니들이게맛을','M','010-8997-1122','울릉도');
INSERT INTO KHACADEMY
VALUES(5,'mslove','5555','김민수','영원한ms','F',default,'서울시');

select * from KHACADEMY;

update khacademy
set pass='9999'
where NICKNAME='내눈은말똥';

update khacademy
set tel = '없음'
where tel='010-0000-0000';

delete from khacademy where ID='sin';

truncate table khacademy;


CREATE TABLE MEMBER_TEST
(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(20),
	USER_PWD CHAR(20)
);

SELECT * FROM MEMBER_TEST;

-- 이미 생성된 테이블에 새로운 컬럼 (유저 이름 : USER_NAME VARCHAR(20))
ALTER TABLE MEMBER_TEST ADD(USER_NAME VARCHAR(20));

-- 확인
SELECT * FROM MEMBER_TEST;

-- 구조 확인
DESC MEMBER_TEST;

-- 새로운 컬럼 추가 및 DEFAULT 값 설정
-- (나이 : USER_AGE NUMBER  / 기본값 : 0)
ALTER TABLE MEMBER_TEST ADD(USER_AGE NUMBER DEFAULT 0);

INSERT INTO MEMBER_TEST
VALUES(1,'USER11','1111','홍길동',DEFAULT);

SELECT * FROM MEMBER_TEST;

-- 제약조건이 없으면 중복된 ID가 저장됨
INSERT INTO MEMBER_TEST
VALUES(2,'USER11','1111','홍길동',DEFAULT);

-- 테이블의 설정된 제약조건 확인
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME='MEMBER_TEST'
UNION
SELECT TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='MEMBER_TEST'
ORDER BY 3 DESC;


-- 제약 조건 추가
-- 형식
-- ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건이름 제약조건(컬럼)
delete from member_test where user_no='1';
ALTER TABLE MEMBER_TEST
ADD CONSTRAINT MEMBER_ID_UNQ UNIQUE(USER_ID);

-- NOT NULL 제약 조건을 추가할때에는 ADD가 아닌 MODIFY로 해야함
ALTER TABLE MEMBER_TEST
MODIFY USER_PWD CONSTRAINT MEMBER_PWD_NN NOT NULL;


-- 컬럼명 수정
-- USER_PWD -> PASSWORD

ALTER TABLE MEMBER_TEST
RENAME COLUMN USER_PWD TO PASSWORD;

SELECT * FROM MEMBER_TEST;

-- 컬럼의 데이터 타입 수정
-- USER_NAME VARCHAR2(20) -> CHAR(30)

ALTER TABLE MEMBER_TEST
MODIFY USER_NAME CHAR(30);
DESC MEMBER_TEST;

-- DEFAULT 값 수정
-- USER_AGE의 DEFAULT 값 수정 (0 -> 99)

ALTER TABLE MEMBER_TEST
MODIFY USER_AGE DEFAULT 99;

-- 컬럼 삭제
-- USER_AGE 컬럼 삭제

ALTER TABLE MEMBER_TEST
DROP COLUMN USER_AGE;
SELECT * FROM MEMBER_TEST;

-- 간단 예제
-- MEMBER_TEST01 테이블의 USER_ID를
-- MEMBER_FOREIGN 테이블에서 참조(외래키 설정)하고 있을 때
-- MEMBER_TEST01 테이블에서 USER_ID를 삭제 하고 싶을 때
SELECT * FROM MEMBER_TEST01;
SELECT * FROM MEMBER_FOREIGN;

-- 해당 컬럼을 삭제 할 때 제약조건이 연결되어 있다면
-- 해당 제약조건도 모두 삭제하면서 컬럼을 지우는 SQL
ALTER TABLE MEMBER_TEST01
DROP COLUMN USER_ID CASCADE CONSTRAINTS;
SELECT * FROM MEMBER_TEST01;
-- 제약 조건 삭제
-- 설정되어 있는 제약조건을 삭제 할 수 있음
-- 테이블의 설정된 제약조건 확인
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME='MEMBER_TEST'
UNION
SELECT TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='MEMBER_TEST'
ORDER BY 3 DESC;

-- MEMBER_TEST 테이블에 설정된 UNIQUE 제약 조건 삭제
ALTER TABLE MEMBER_TEST
DROP CONSTRAINT MEMBER_ID_UNQ;

-- 제약조건 이름 변경
-- 설정되어 있는 제약조건의 이름을 변경 할 수 있음

ALTER TABLE MEMBER_TEST
RENAME CONSTRAINT SYS_C007117 TO MEMBER_NUM_PK;

-- 테이블 이름 변경
-- 생성된 테이블이 이름 변경이 가능함
ALTER TABLE MEMBER_TEST
RENAME TO MEMBER_TEST_TBL;

SELECT * FROM MEMBER_TEST_TBL;

-- 테이블 삭제
-- DROP 명령어를 통해 테이블 삭제가 가능함
DROP TABLE MEMBER_TEST_TBL;
-- 혹은 연결된 제약조건을 모두 함께 삭제할 수도 있음
DROP TABLE MEMBER_TEST_TBL CASCADE CONSTRAINTS;

