-- Stored Procedure

CREATE TABLE EMP AS SELECT * FROM EMPLOYEE;

SELECT * FROM EMP;


CREATE PROCEDURE EMP_ID_DEL(ID EMP.EMP_ID%TYPE)
IS
BEGIN
    DELETE FROM EMP WHERE EMP_ID = ID;
END;
/

EXECUTE EMP_ID_DEL('&사원번호');


CREATE OR REPLACE PROCEDURE EMP_SEARCH
            (D_CODE EMP.DEPT_CODE%TYPE := 'D1', 
             J_CODE EMP.JOB_CODE%TYPE := 'J6')
IS
    ID EMP.EMP_ID%TYPE;
    NAME EMP.EMP_NAME%TYPE;
BEGIN
    SELECT EMP_ID, EMP_NAME
    INTO ID, NAME
    FROM EMP
    WHERE DEPT_CODE = D_CODE AND JOB_CODE = J_CODE AND
    ROWNUM = 1;
    DBMS_OUTPUT.PUT_LINE('사번 : ' || ID);
    DBMS_OUTPUT.PUT_LINE('이름 : ' || NAME);
    EXCEPTION
    WHEN NO_DATA_FOUND
    THEN DBMS_OUTPUT.PUT_LINE('찾을수가 없습니다');
END;
/

EXEC EMP_SEARCH('D6','J3');
EXEC EMP_SEARCH('D8');
EXEC EMP_SEARCH();

CREATE OR REPLACE PROCEDURE EMP_MODIFY_SALARY
            (ID EMP.EMP_ID%TYPE, SAL EMP.SALARY%TYPE)
IS
    before_SAL EMP.SALARY%TYPE;
    after_SAL EMP.SALARY%TYPE;
    NAME EMP.EMP_NAME%TYPE;
BEGIN
    SELECT SALARY
    INTO before_SAL
    FROM EMP
    WHERE EMP_ID=ID;
    
    UPDATE EMP
    SET SALARY = SAL
    WHERE EMP_ID = ID;
    
    SELECT EMP_NAME,SALARY
    INTO NAME,after_SAL
    FROM EMP
    WHERE EMP_ID = ID;
    
    DBMS_OUTPUT.PUT_LINE(NAME||'사원의 급여 변경');
    DBMS_OUTPUT.PUT_LINE(before_SAL||'->'||after_SAL);
END;
/

EXEC EMP_MODIFY_SALARY('201',3000000);

SELECT * FROM EMP;

