SELECT EMP_ID AS "사원번호", EMP_NAME AS "사원명", RPAD(SUBSTR(EMP_NO,1,7),14,'*') AS " 주민번호", SALARY*12 AS "연봉" FROM EMPLOYEE WHERE EMP_NO LIKE '%-1%';

SELECT LOWER('Welecome To My Oracle World') FROM DUAL;
SELECT UPPER('Welecome To My Oracle World') FROM DUAL;
SELECT INITCAP('welecome to my oracle world') FROM DUAL;

SELECT CONCAT(CONCAT('가나다','ABC'),'123') FROM DUAL;
SELECT '가나다'||'ABC'||'123' FROM DUAL;

SELECT replace('Hello World' ,'Hello','Java') FROM DUAL;

SELECT EMP_NAME, EMP_NO, REPLACE(EMAIL, 'kh','iei') FROM EMPLOYEE;

SELECT ABS(+3) FROM DUAL;
SELECT ABS(-3) FROM DUAL;

SELECT MOD(10,3) FROM DUAL;

SELECT TRUNC(123.456,2) FROM DUAL;
SELECT TRUNC(123.456,1) FROM DUAL;
SELECT TRUNC(123.456,0) FROM DUAL;
SELECT TRUNC(123.456,-1) FROM DUAL;
SELECT TRUNC(123.456,-2) FROM DUAL;

SELECT CEIL(123.456) FROM DUAL;

SELECT CURRENT_DATE FROM DUAL;
SELECT LOCALTIMESTAMP FROM DUAL;
SELECT CURRENT_TIMESTAMP FROM DUAL;


SELECT EMP_NAME, FLOOR(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS "개월",
HIRE_DATE,
SYSDATE
FROM EMPLOYEE;

SELECT EMP_NAME, HIRE_DATE, ADD_MONTHS(HIRE_DATE,6)
FROM EMPLOYEE;

SELECT SYSDATE AS "재입대일",
ADD_MONTHS(SYSDATE,18) AS "제대일자",
(ADD_MONTHS(SYSDATE,18)-SYSDATE)*3 AS "짬밥그릇"
FROM DUAL;

SELECT SYSDATE,NEXT_DAY(SYSDATE,'수요일') FROM DUAL;
SELECT SYSDATE,NEXT_DAY(SYSDATE,'수') FROM DUAL;
SELECT SYSDATE,NEXT_DAY(SYSDATE,4) FROM DUAL;

SELECT LAST_DAY('20/02/01') FROM DUAL;

SELECT EXTRACT (YEAR FROM SYSDATE) FROM DUAL;
SELECT EXTRACT (MONTH FROM SYSDATE) FROM DUAL;
SELECT EXTRACT (DAY FROM SYSDATE) FROM DUAL;

SELECT EMP_NAME AS "이름",
EXTRACT(YEAR FROM HIRE_DATE)||'년 '
|| EXTRACT(MONTH FROM HIRE_DATE) || '월 '
|| EXTRACT(DAY FROM HIRE_DATE) || '일' AS "입사일",
CEIL(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/365) AS "년차"
FROM EMPLOYEE
ORDER BY "년차";

SELECT EMP_NAME AS "이름",
HIRE_DATE AS "입사일",
(LAST_DAY(HIRE_DATE)+1) AS "기준일",
ADD_MONTHS((LAST_DAY(HIRE_DATE)+1),6) AS "기준일+6",
EXTRACT (MONTH FROM ADD_MONTHS((LAST_DAY(HIRE_DATE)+1),6))||'월' AS "기준달(월)"
FROM EMPLOYEE
ORDER BY "입사일";

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY/MON/DD/DAY') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY/MONTH/DD/DAY') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD/HH12"시"MI"분"SS"초"') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD/HH24"시"MI"분"SS"초"') FROM DUAL;

SELECT EMP_NAME AS "이름", TO_CHAR(HIRE_DATE, 'YYYY/MM/DD(DY)') AS "고용일" FROM EMPLOYEE;

SELECT TO_CHAR(100000000,'999,999,999') FROM DUAL;
SELECT TO_CHAR(100000000,'$999,999,999') FROM DUAL;
SELECT TO_CHAR(100000000,'l999,999,999') FROM DUAL;
SELECT TO_CHAR(100000000,'999,999,999.999') FROM DUAL;

SELECT TO_DATE(20010101,'YYYY/MM/DD') FROM DUAL;
SELECT TO_CHAR(TO_DATE(20010101,'YYYY/MM/DD'),'YYYY/MM/DD') FROM DUAL;
SELECT TO_CHAR(TO_DATE(20010101,'YYYY/MM/DD'),'YYYY/MM/DD HH24:MI:SS') FROM DUAL;


SELECT TO_CHAR(TO_NUMBER('1,000,000','9,999,999')
-TO_NUMBER('500,000','999,999'),'999,999') FROM DUAL;

SELECT TO_NUMBER('A1,000,000','999,999,999') FROM DUAL;
SELECT TO_NUMBER('$1,000,000','999,999,999') FROM DUAL;
SELECT TO_NUMBER('$1,000,000','$999,999,999') FROM DUAL;

SELECT NVL(BONUS,0)
FROM EMPLOYEE;

SELECT EMP_NAME, DECODE(SUBSTR(EMP_NO,8,1),'1','남자','2','여자')
FROM EMPLOYEE;

SELECT EMP_NAME, DECODE(SUBSTR(EMP_NO,1,2),
'61','소띠',
'62','호랑이띠',
'63','토끼띠',
'64','용띠',
'65','뱀띠',
'66','말띠',
'67','양띠',
'68','원숭이띠',
'69','닭띠')
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,1,2) BETWEEN 60 AND 69;

SELECT EMP_NAME, CASE WHEN SUBSTR(EMP_NO,8,1) = 1 THEN '남자'
WHEN SUBSTR(EMP_NO,8,1) = 2 THEN '여자'
END
FROM EMPLOYEE;

SELECT EMP_NAME,
CASE WHEN SUBSTR(EMP_NO,3,2) BETWEEN 3 AND 5 THEN '봄 태생'
WHEN SUBSTR(EMP_NO,3,2) BETWEEN 6 AND 8 THEN '여름 태생'
WHEN SUBSTR(EMP_NO,3,2) BETWEEN 9 AND 11 THEN '가을 태생'
ELSE '겨울 태생'
END
FROM EMPLOYEE;

SELECT SUM(SALARY) FROM EMPLOYEE;
SELECT AVG(SALARY) FROM EMPLOYEE;
SELECT SUM(SALARY),COUNT(*) FROM EMPLOYEE;
SELECT MIN(SALARY), MAX(SALARY) FROM EMPLOYEE;

SELECT EMP_NAME AS "직원명",
EMAIL AS "이메일",
LENGTH(EMAIL) AS "이메일길이"
FROM EMPLOYEE;

SELECT EMP_NAME AS "이름",
SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1)
FROM EMPLOYEE;

SELECT EMP_NAME AS "직원명",
SUBSTR(EMP_NO,1,2) AS "년생",
NVL(BONUS,0) AS "보너스"
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,1,2) BETWEEN 60 AND 69;

SELECT COUNT(PHONE)||'명'
FROM EMPLOYEE
WHERE PHONE NOT LIKE '010%';

SELECT EMP_NAME AS "직원명",
TO_CHAR(HIRE_DATE,'YYYY"년"MON') AS "입사년월"
FROM EMPLOYEE;

select emp_name as "직원명",
RPAD(SUBSTR(EMP_NO,1,8),14,'*')
FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT EMP_NAME AS "직원명",
JOB_CODE AS "직급코드",
TO_CHAR(((NVL(BONUS,0)*SALARY*12)+SALARY*12),'L999,999,999')||'원' AS "연봉"
FROM EMPLOYEE;

SELECT EMP_ID AS "사번",
EMP_NAME AS "사원명",
DEPT_CODE AS "부서코드",
HIRE_DATE AS "입사일"
FROM EMPLOYEE
WHERE (DEPT_CODE = 'D5' OR DEPT_CODE = 'D9')
AND EXTRACT(YEAR FROM HIRE_DATE)='2004';

SELECT EMP_NAME AS "직원명",
HIRE_DATE AS "입사일",
FLOOR((SYSDATE-HIRE_DATE)) AS "근무일수"
FROM EMPLOYEE;

SELECT EMP_NO
FROM EMPLOYEE;

SELECT MAX(TO_CHAR(EXTRACT(YEAR FROM SYSDATE)-LPAD(SUBSTR(EMP_NO,1,2),4,19))) AS "나이 많음", 
MIN(TO_CHAR(EXTRACT(YEAR FROM SYSDATE)-LPAD(SUBSTR(EMP_NO,1,2),4,19))) AS "나이 적음"
FROM EMPLOYEE;

SELECT EMP_NAME AS "이름",
DEPT_CODE AS "부서코드",
CASE WHEN DEPT_CODE='D5'OR DEPT_CODE='D6' OR DEPT_CODE='D9' THEN '야근'
ELSE '야근없음' 
END
AS "야근유무"
FROM EMPLOYEE
ORDER BY 2;